### ISSUE TITLE
GetUser feature

### ISSUE THREAD

**Issue by maitojepoy** [jagregory/cognito-local#3]
Hi @jagregory,

Would it be possible for you to add a feature on [GetUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html)? I guess this is included in your roadmap since you already have added ListUsers feature.

**Comment by jagregory** [comment]
It's not specifically on my roadmap (I'm mostly just implementing the things I currently use). If I get some free time soon I'll take a look, otherwise as you know PRs are welcome. It's probably pretty easy to copy the listUsers implementation and tweak it.

What might a minimal implementation look like? Is it as simple as:

1. Parse the AccessToken
2. Extract the sub field
3. Return the user if it exists

**Comment by maitojepoy** [comment]
Okay @jagregory. I will try to implement it :)

**Comment by jagregory** [comment]
Closed by #4
