### ISSUE TITLE
Feature Request: Flag to allow actual aws cognito errors to be thrown

### ISSUE THREAD

**Issue by codyburrito** [jagregory/cognito-local#309]
Currently cognito-local returns custom errors defined in [errors.ts](https://github.com/jagregory/cognito-local/blob/master/src/errors.ts).  This means you may have to write custom error handler code just for cognito-local which is less than ideal.  

I assume throwing actual aws cognito errors by default will be a breaking change so this will probably have to be a flag that is `false` by default.

I may be able to work on this soon!

**Comment by charlieparkes-BO** [comment]
Just ran into this. What's the point of mocking cognito if the mock returns incorrect error codes?

**Comment by jagregory** [comment]
I've merged @paullallier's changes, which should fix some of the issues you've all been seeing. I'm going to close this issue assuming Paul's changes work for everyone, but please reopen if that's not the case. [v3.21.2](https://github.com/jagregory/cognito-local/releases/tag/v3.21.2)

Just for clarity, this repo has a suite of integration tests which use the actual NodeJS AWS SDK to test these APIs with error handling, so it was my understanding that _I was actually using the correct Cognito errors_! It wasn't intentional that cognito-local would have a different set of error codes to the actual Cognito, that defeats the object of an emulator entirely. These issues appear to be variations in how the different SDKs handle errors (and I assume the NodeJS SDK is more lenient than others).

I'm happy to accept PRs to fix these issues, but unfortunately I don't have any means to reproduce these issues myself, so PRs will have to be accepted on good faith that they fix issues.
