### ISSUE TITLE
Confirmation code not being printed in cognito-local logs

### ISSUE THREAD

**Issue by piyushk-sony** [jagregory/cognito-local#382]
I'm using cognito-local with a simple full stack example to allow our users to add auth during local testing of the stack without having to provision a Cognito User Pool in AWS. I'm using it via docker (`jagregory/cognito-local:latest`) and docker-compose and the default configuration.

The README suggests that confirmation codes should be printed in the logs https://github.com/jagregory/cognito-local#confirmation-codes,. Is there a configuration option I need to enable to print those confirmations to the screen? I have confirmed that the SignUp request is being received and processed by Cognito-local and the user is added with "UserStatus" as "UNCOMFIRMED", but no sign up code is printed on the screen.

Notes:
- I can log in via the uncomfirmed user due to outstanding ticket https://github.com/jagregory/cognito-local/issues/122
- Setting the environment variable CODE=123456 (as noted in https://github.com/jagregory/cognito-local/pull/340) seems to be working as expected to confirm the user. This might be good enough for my use-case, but I was surprised to see the confirmation code not printing without the CODE env var.

**Comment by jagregory** [comment]
Hey @piyushk-sony, sorry to hear you're having issues. The console logging does work (I use it myself), but there might be some combination of user pool setting you're missing or unexpected behaviour of cognito-local vs real cognito.

When a user signs up, a combination of the pool's `AutoVerifiedAttributes` and the user's `Attributes` are used to determine if a code should be sent to them. If it is sent it will be printed to the console.

For example, your user pool should have an `AutoVerifiedAttributes` set to `email` and your user should have an `email` attribute. If both of those aren't true a code won't be sent/printed. I can see your user has the `email` attribute, does your user pool have `AutoVerifiedAttributes` set?

This is the logic:

https://github.com/jagregory/cognito-local/blob/161d4f69821f655c62ee4a5d7f2d9da06939ab73/src/targets/signUp.ts#L37-L50

https://github.com/jagregory/cognito-local/blob/161d4f69821f655c62ee4a5d7f2d9da06939ab73/src/services/messageDelivery/deliveryMethod.ts#L5-L32

As for `GetUserAttributeVerificationCode` not working, that definitely sounds like a legit issue. Possibly the code isn't being saved against the user because of the above logic, when it should be saved even if the message isn't sent.

**Comment by piyushk-sony** [comment]
Thanks a lot @jagregory. That was exactly it. Creating the `user-pool` with ` --auto-verified-attributes email` shows the confirmation code output.
